### PR TITLE
Added the BUILD_DIR flag

### PR DESCRIPTION
**Pull request by ThaumicMekanism**
I have added a flag to set the build directory just in case you want to touch up that directory before it gets used.

### CODE REVIEW

**Comment by helaili** [comment]
Thanks @ThaumicMekanism. Can I ask you what is the use case for this option? I see `BUILD_DIR` as a temporary folder, so I don't know what is the benefit of setting it arbitrarily.

**Comment by ThaumicMekanism** [comment]
I was having some issues with Jekyll not copying over some files so I had a preprocessor command to do so. The problem is I have to copy the path used by this which has changed in the past. This way, changes to it will not break that kind of setup (like if you need to preprocess something in that folder).

**Comment by fsimonis** [comment]
The proposed flag would make your action easier to use for build-only workflows.

We are using this action to build our jekyll site. https://github.com/precice/precice.github.io
For PRs we use `build_only: true` and upload the site as an artifact.

Currently this requires us to hard-code `/github/jekyll_build`, which may change any moment :)

**Comment by itrich** [comment]
:+1: I support this PR. We're using https://github.com/Burnett01/rsync-deployments to push the build result to a remote directory. However, this action can't access directories outside of `${GITHUB_WORKSPACE}`. If I explicitly set the output dir as an jekyll parameter (e.g. `-d _site`), the build result is not pushed since `${BUILD_DIR}` is hard-coded.

I'd be happy if this PR gets merged.

**Comment by fullbright** [comment]
I support also this PR. We are using https://phpqa.io/projects/html-proofer.html to check the quality of our code before publishing. We are having issues because the build dir is hidden and not accessible from outside the container.

I'd be happy if this PR gets merged.

**Comment by dwisiswant0** [comment]
Any updates on this, @helaili?

**Comment by helaili** [comment]
Sort of messed up this PR so using #138 to merge this change. Sorry for the confusion

**Pull request closed without merging**
