### PR TITLE
Supported custom Gemfile location

### PR DESCRIPTION
**Pull request by r4zzz4k**
Coming out of discussions in #31 and #32, here's an implementation based on `--gemfile` parameter of Jekyll. This is highly inspired by limjh16/jekyll-action-ts@7b4b016 with the difference of adding deployment mode for Jekyll instead of pinning `vendor/bundle` location. Seems that Bundler places `vendor/bundle` near `Gemfile` (so `--gemfile` changes it's location) in deployment mode, but I'm not seeing how this could prevent caching as one can setup arbitrary path to cache in corresponding action. Deployment mode should also help with situations where Gemfile is not synced with Gemfile.lock. It seems to be recommended way to run CI jobs.

Here's the proof search works as expected, including skipped Gemfile inside `docs/vendor/bundle` (reason for a change to `find` invocations):
https://github.com/r4zzz4k/inkremental/runs/694177170?check_suite_focus=true
In the final run I've decided to leave both variables to be set though.

It also seems that entrypoint script doesn't use positional arguments, so I've removed one from `action.yml`. Also I've cleaned up logging a bit.

### CODE REVIEW

**Comment by limjh16** [comment]
Hey! I decided to pin the vendor/bundle location since it required little configuration, so that the workflow.yml file is just "plug and play". Would there be any issues when the vendor/bundle location is pinned?

**Comment by r4zzz4k** [comment]
No issues coming to my mind, but without any experience with Ruby ecosystem I can't be sure. But I agree that it's more convenient to just copy-paste default cache configuration proposed by GitHub and projects' READMEs. I guess I'll pin cache location with separate commit to allow for simple rollback if needed, leaving `find` changes in place as these won't hurt anything.

**Comment by r4zzz4k** [comment]
Plain `bundle config path "$PWD/vendor/bundle"` is still pointing to a directory with `Gemfile` as I mentioned earlier, probably due to `--deployment`, so I've pinned it down to an absolute path. Seems to be working for me:
https://github.com/r4zzz4k/inkremental/runs/695982924?check_suite_focus=true
(Bundler says *Bundled gems are installed into `./vendor/bundle`* instead of *Bundled gems are installed into `./docs/vendor/bundle`* as it was previously; cache is also setup to `vendor/bundle` directory, Bundler seems to consume it successfully).

**Comment by r4zzz4k** [comment]
@helaili could you please take a look at your convenience?

**Comment by helaili** [comment]
Thanks @r4zzz4k and @limjh16 for this ✨ contribution. It works great but I'm still a bit torn about `jekyll_src` vs `gem_src`. Should we manage it as followed: 
1. Use `gem_src` when provided, 
1. If not, look into `jekyll_src`, 
1. If still not found, lookup for `Gemfile.lock`. 

My thinking is it would allow to locate the whole site including the `Gemfile` into a single directory without having to specify both parameters. Therefore the `gem_src` parameter would only be needed in very few use cases, but we will still have the capability of leveraging a different `Gemfile`.

**Comment by r4zzz4k** [comment]
I didn't consider such solution as I thought this would be a breaking change, but your proposed flow seems to fallback properly for current users. Sounds nice!

**Comment by r4zzz4k** [comment]
Sorry for the long delay.
Here's a test run with this commit: https://github.com/r4zzz4k/inkremental/actions/runs/124072756
Note that only `jekyll_src` is set, and debug logging mentions it successfully set Gem directory (`GEM_SRC`) via source directory (`JEKYLL_SRC`).

**Comment by r4zzz4k** [comment]
@helaili did I get your idea correctly?

**Comment by helaili** [comment]
I've added some tests but I'm having a weird behavior on my machine, so could you just do a quick push on your fork to trigger the worklflow, so we make sure various use cases are 👍 ?

**Comment by r4zzz4k** [comment]
Here you are: https://github.com/r4zzz4k/inkremental/runs/743811330
https://inkremental.r4zzz4k.me/

Seems to be working: run got the last commit, went fine, reused cache, found everything as expected:
``` ##[debug]Source directory is set via input parameter
##[debug]Using "docs" as a source directory
##[debug]Gem directory is set via source directory
##[debug]Using "docs" as Gem directory
```

**Comment by r4zzz4k** [comment]
Oh, sorry, you've ment push in the fork of the action... Just a moment!

**Comment by r4zzz4k** [comment]
https://github.com/r4zzz4k/jekyll-action/runs/743846405
Action run successfully, but https://github.com/r4zzz4k/jekyll-action/tree/gh-pages holds unprocessed `adoc`-s for some reason, though file locations seem to correspond to Jekyll output. Not sure what's going on.

**Comment by helaili** [comment]
I guess it means the Jekyll plugins aren't executed, I'll dig into this.

**Comment by helaili** [comment]
So I got it to work @r4zzz4k but there might be a better solution, this one is a bit hacky.  Also, I need to wrap my head around the possible side effects and edge cases. One that comes to mind immediately is when `Gemfile` is already at the root of the workspace, so we should test for this and not do the `cp` in this case.

**Comment by r4zzz4k** [comment]
Yeah, I saw your changes and I'm not sure why this was needed here for testing purposes but wasn't needed for my site (https://github.com/helaili/jekyll-action/pull/35#issuecomment-639829916). I'll look into this when I get to my PC.

**Comment by helaili** [comment]
I'm not too sure either. The `jekyll-feed` plugin you use seems to run in your case, while mine, `jekyll-asciidoc`, seems to be silently failing.

**Comment by r4zzz4k** [comment]
Okay, I ran through the logs again and this caught my attention:
```##[debug]Using "./sample_site_jekyll
./sample_site" as a source directory```
This is obviously incorrect, and the script didn't expect to find two Jekyll sites in the repo :) Will fix that and see how it goes without copying Gemfile first.

**Comment by r4zzz4k** [comment]
And surely "Basic run" is actually impossible to test in directory where there are two Jekyll sites as it searches specifically for one site.

**Comment by r4zzz4k** [comment]
Here you are, now we have a proper error for this situation:
https://github.com/r4zzz4k/jekyll-action/runs/757363501

**Comment by helaili** [comment]
So I was still bugged by `jekyll_asciidoc` not being triggered. Seems like Jekyll needs to run from where the `Gemfile` is in order to trigger the plugin properly. I tried to `cd` as opposed to providing `bundler` args and it seems to work. 

I have also changed test cases so everything passes and allow enabling of Jekyll verbose output (need to document this).

**Comment by r4zzz4k** [comment]
Sorry, I've completely lost you at the issue with asciidoc. Nice to see it's working for you, checked that it's also still working for my site. I'm okay with latest changes.

Should I rebase on fresh master and rewrite history or would you merge this as is?

**Comment by helaili** [comment]
Ooops, forgot to merge this PR. Thanks @r4zzz4k, this is good as is 👍

**Pull request merged**
